### PR TITLE
Upgraded to VS2022

### PR DESCRIPTION
**Pull request by TTimo**

### CODE REVIEW

**Comment by TTimo** [comment]
@justcla would you consider merging https://github.com/TTimo/EmacsKeys/commit/62ef612877d97675ee85440657413cb729865822 in your release? (see https://github.com/zbrad/EmacsKeys/issues/16)

Only reason I maintain this fork myself..

**Comment by justcla** [comment]
My concern is that it will enable Delete Selection Mode without any way to turn it off.
This might be unexpected behaviour for many users.
Is there a way to toggle the setting on and off. If so, the merged changed should default the setting to be the same as it is now. Then it becomes opt-in instead of "what the hell just happened to my code?!"

**Comment by justcla** [comment]
Looking further into it, I notice that M-x (Alt-X) is the standard shortcut to toggle Delete-Selection-Mode on and off.
Would you consider adding a new command that toggles delete-selection-mode?

Ideally, the setting should persist through VS restarts. For that, I would save the setting in the UserSettingStore and read it back in when the extension initializes. (Examples of that exist in the [KeyboardShortcutsManager](https://github.com/justcla/VSShortcutsManager/blob/0b31b4c8e958aee45798fea6ce025faf15498f38/VSShortcutsManager/UserShortcutsManager.cs) - if you want to try implementing that.)

**Comment by justcla** [comment]
I note this feature has been previously requested from other users. If you were able to bring this into this extension (with a toggle switch, and off by default), it will be most welcome!

**Comment by TTimo** [comment]
@justcla I hardly know anything about C# or Visual Studio extensions, adding some configurable setting for this won't be trivial for me. Are you suggesting this should be done via some silent M-x shortcut (that doesn't sound right), or maybe with some option page? (I found this: https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-an-options-page?view=vs-2022 - might be helpful?)

**Comment by justcla** [comment]
Well, yes. I notice that normal Emacs behaviour uses M-x to toggle in and out of delete selection mode.
But, creating a new command is not always that easy. Worse still, the VSK with all the key bindings was built many years ago and there is no vssettings file from which to recreate it. (However, one could be generated and grabbed fun the folder in AppData.)

Otherwise, the Options Page might be an easier thing to implement. But the user will need to go into the settings to turn it off and on.

**Comment by justcla** [comment]
I don't love this extension enough to struggle with it. Maybe you could publish your version on the Marketplace for people who prefer delete selection mode anyways on.

**Pull request merged**
